# Generated by Django 3.2.9 on 2021-11-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('short_name', models.CharField(max_length=3, unique=True)),
                ('square', models.IntegerField()),
                ('total_stars', models.IntegerField()),
                ('symbol', models.FileField(upload_to='symbols/')),
            ],
            options={
                'verbose_name': 'Constellation',
                'verbose_name_plural': 'Constellations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constellations.constellation')),
            ],
            options={
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
                'ordering': ['name'],
            },
        ),
    ]
