# Generated by Django 3.2.9 on 2021-11-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0002_alter_constellation_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='zodiac',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
