# Generated by Django 3.2.9 on 2021-11-29 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constellations', '0003_constellation_zodiac'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constellations', to=settings.AUTH_USER_MODEL),
        ),
    ]
